// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceExploreCrewService.DataLayer;

namespace SpaceExploreCrewService.Migrations
{
    [DbContext(typeof(CrewServiceDBContext))]
    [Migration("20200802132027_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceExploreCrewService.DataLayer.Entities.Captain", b =>
                {
                    b.Property<int>("CaptainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaptainId");

                    b.ToTable("Captains");
                });

            modelBuilder.Entity("SpaceExploreCrewService.DataLayer.Entities.Crew", b =>
                {
                    b.Property<int>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaptainId")
                        .HasColumnType("int");

                    b.Property<int>("ShuttleId")
                        .HasColumnType("int");

                    b.HasKey("CrewId");

                    b.HasIndex("CaptainId")
                        .IsUnique();

                    b.HasIndex("ShuttleId")
                        .IsUnique();

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("SpaceExploreCrewService.DataLayer.Entities.Robot", b =>
                {
                    b.Property<int>("RobotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<string>("RobotName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RobotId");

                    b.HasIndex("CrewId");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("SpaceExploreCrewService.DataLayer.Entities.Shuttle", b =>
                {
                    b.Property<int>("ShuttleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShuttleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShuttleTire")
                        .HasColumnType("int");

                    b.HasKey("ShuttleId");

                    b.ToTable("Shuttles");
                });

            modelBuilder.Entity("SpaceExploreCrewService.DataLayer.Entities.Crew", b =>
                {
                    b.HasOne("SpaceExploreCrewService.DataLayer.Entities.Captain", "Captain")
                        .WithOne("Crew")
                        .HasForeignKey("SpaceExploreCrewService.DataLayer.Entities.Crew", "CaptainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceExploreCrewService.DataLayer.Entities.Shuttle", "Shuttle")
                        .WithOne("Crew")
                        .HasForeignKey("SpaceExploreCrewService.DataLayer.Entities.Crew", "ShuttleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceExploreCrewService.DataLayer.Entities.Robot", b =>
                {
                    b.HasOne("SpaceExploreCrewService.DataLayer.Entities.Crew", "Crew")
                        .WithMany("Robot")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
